HA$PBExportHeader$u_bri_2004_pr_lista_brigadas_no_disp.sru
forward
global type u_bri_2004_pr_lista_brigadas_no_disp from u_gen_0000_lista
end type
end forward

global type u_bri_2004_pr_lista_brigadas_no_disp from u_gen_0000_lista
int Width=1811
string DataObject="d_bri_2004_pr_lista_brigadas"
end type
global u_bri_2004_pr_lista_brigadas_no_disp u_bri_2004_pr_lista_brigadas_no_disp

