HA$PBExportHeader$u_bri_2004_pr_lista_brigadas_disponibles.sru
forward
global type u_bri_2004_pr_lista_brigadas_disponibles from u_gen_0000_lista
end type
end forward

global type u_bri_2004_pr_lista_brigadas_disponibles from u_gen_0000_lista
int Width=2117
string DataObject="d_bri_2004_pr_lista_brigadas_disp"
end type
global u_bri_2004_pr_lista_brigadas_disponibles u_bri_2004_pr_lista_brigadas_disponibles

