HA$PBExportHeader$u_bri_2013_pr_brigadistas_disponibles.sru
forward
global type u_bri_2013_pr_brigadistas_disponibles from u_gen_0000_lista
end type
end forward

global type u_bri_2013_pr_brigadistas_disponibles from u_gen_0000_lista
int Width=1025
int Height=845
int TabOrder=1
string DataObject="d_bri_2013_brigadistas_disponibles"
boolean VScrollBar=true
boolean LiveScroll=true
end type
global u_bri_2013_pr_brigadistas_disponibles u_bri_2013_pr_brigadistas_disponibles

